---
title: "Hobo temperature loggers"
author: "Molly Wilson"
date: "2024-10-09"
output: html_document
---


```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(janitor)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

```{r}
cades <- read_excel(here("restoration_monitoring", "data_raw", "hobo", "Cades.xlsx"), 
                  sheet = 1) %>%
  clean_names() %>%
  dplyr::rename(date = 2, temp_c = 3) %>%
  select(-number) %>%
  mutate(nursery = "Cades")

tpb <- read_excel(here("restoration_monitoring", "data_raw", "hobo", "Ten pound bay.xlsx"), 
                  sheet = 1) %>%
  clean_names() %>%
  dplyr::rename(date = 2, temp_c = 3) %>%
  select(-number) %>%
  mutate(nursery = "Ten Pound Bay")

deep <- read_excel(here("restoration_monitoring", "data_raw", "hobo", "Deep water.xlsx"), 
                  sheet = 1) %>%
  clean_names() %>%
  dplyr::rename(date = 2, temp_c = 3) %>%
  select(-number) %>%
  mutate(nursery = "Deep Nursery")

temp_data <- rbind(cades, tpb, deep) %>%
  filter(temp_c < 32) # removing outlyers from loggers being on the boat and heating up

ref_temp_bleaching = 30.63

ggplot(temp_data,
       aes(x = date, y = temp_c, color = nursery)) +
  geom_line(alpha = 0.9, size = 0.3) +
  scale_color_manual(values = c("cadetblue", "coral", "gold")) +
  geom_hline(yintercept = ref_temp_bleaching, linetype = 'dashed') +
  scale_y_continuous(sec.axis = sec_axis(~.*9/5+32, name = "Temperature (째F)")) +
  labs(x = "", y = "Temperature (째C)", color = "Nursery location") +
  theme_bw() +
  theme(legend.position = "bottom")
ggsave(here("restoration_monitoring", "figs", "hobo_24.10a.png"), width = 6, height = 4)

ggplot(temp_data,
       aes(x = date, y = temp_c)) +
  geom_line(alpha = 0.9, size = 0.3, color = "cadetblue") +
  geom_hline(yintercept = ref_temp_bleaching, linetype = 'dashed', color = "coral") +
  scale_y_continuous(sec.axis = sec_axis(~.*9/5+32, name = "Temperature (째F)")) +
  facet_grid(. ~ nursery) +
  labs(x = "", y = "Temperature (째C)", color = "Nursery") +
  theme_bw()
ggsave(here("restoration_monitoring", "figs", "hobo_24.10b.png"), width = 6, height = 4)
  
```

