---
title: "Genotype master"
author: "Molly Wilson"
date: "2024-03-28"
output: 
  html_document:
    code_folding: hide
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(janitor)
library(snakecase) # for adjusting capitalization of text within data (e.g., species names)
library(knitr) # for including tables
library(stringr)
library(lubridate)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

Nursery locations
```{r}
letter_names <- function(nms) LETTERS[seq_along(nms)]
york <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "York", 
                  range = "A1:F9",
                  col_names = FALSE, 
                  .name_repair = letter_names)
tpb <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "TPB", 
                  range = "A1:B10",
                  col_names = FALSE, 
                  .name_repair = letter_names)
cades <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "Cades", 
                  range = "A1:B4",
                  col_names = FALSE, 
                  .name_repair = letter_names)
genebank <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "Gene banks",
                  col_names = TRUE)
plugs_tiles <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "Plugs and tiles", 
                  col_names = TRUE) %>%
  select(genotype, nursery, location, structure)
lab <- read_excel(here("restoration_monitoring", "data_raw", "Nursery map.xlsx"), 
                  sheet = "Lab", 
                  col_names = TRUE)

structures <- york %>% mutate(row = row_number()) %>%
  pivot_longer(
    cols = -row,
    names_to = "col",
    values_to = "genotype",
    values_drop_na = TRUE
  ) %>%
  mutate(nursery = "York",
         structure = case_when(str_detect(genotype, "GB") ~ "Tree",
                               row <= 3 ~ "Rope",
                               row > 3 ~ "Tree")
           ) %>%
  rbind(tpb %>% mutate(row = row_number()) %>%
          pivot_longer(
              cols = -row,
              names_to = "col",
              values_to = "genotype",
              values_drop_na = TRUE
      ) %>%
  mutate(nursery = "TPB",
         structure = case_when(row <= 4 ~ "Tree",
                               row > 4 ~ "Rope")
           )) %>%
  rbind(cades %>% mutate(row = row_number()) %>%
          pivot_longer(
              cols = -row,
              names_to = "col",
              values_to = "genotype",
              values_drop_na = TRUE
      ) %>%
  mutate(nursery = "Cades",
         structure = case_when(row == 1 ~ "Rope",
                               row > 1 ~ "Tree")
           )) %>%
  unite(location, col, row, sep = "", remove = TRUE) %>%
  mutate(genotype = strsplit(as.character(genotype), " / ")) %>% 
  unnest(genotype) %>%
  select(genotype, nursery, location, structure) %>%
  filter(!str_detect(genotype, 'Empty'),
         !str_detect(genotype, 'GB'),
         !str_detect(genotype, 'BC'),
         genotype != "T",
         genotype != "R") %>%
  rbind(plugs_tiles) %>%
  filter(!is.na(genotype))

nursery_locations <- structures %>%
              select(genotype, nursery, location) %>%
              group_by(genotype, nursery) %>%
              summarise(location = paste(location, collapse=", ")) %>%
              pivot_wider(names_from = nursery, values_from = location) %>%
              rename(york_locations = "York",
                     tpb_locations = "TPB",
                     cades_locations = "Cades") %>%
  left_join(structures %>%
              group_by(genotype, structure) %>%
              summarise(n = n()) %>%
              pivot_wider(names_from = structure, values_from = n) %>%
              rename(n_trees = Tree,
                     n_ropes = Rope)
            ) %>%
  full_join(genebank %>%
              unite("location", nursery:location) %>%
              group_by(genotype) %>%
              summarise(gb_locations = paste(location, collapse=", "))
              ) %>%
  left_join(lab %>%
              select(genotype) %>%
              mutate(lab = "Y")) %>%
  select(genotype, york_locations, tpb_locations, cades_locations, gb_locations, lab, n_ropes, n_trees) %>%
  mutate_at(c('york_locations', 'tpb_locations', 'cades_locations', 'gb_locations'), 
            ~replace_na(.,"")) %>%
  mutate_at(c('n_ropes', 'n_trees'), ~replace_na(.,0)) %>%
  mutate_at('lab', ~replace_na(.,"N"))
```


Collection and outplant data
```{r}
# import various datasets to merge
collection <- read_excel(here("restoration_monitoring", "data_raw", "Genotype tracking.xlsx"), sheet = "collection") %>%
  clean_names() %>%
  rename(collection_site = site,
         collection_lat = lat,
         collection_lon = lon)

outplants <- read_excel(here("restoration_monitoring", "data_raw", "Genotype tracking.xlsx"), sheet = "outplants") %>% 
  clean_names() %>%
  mutate(genotype = substr(id, 1, 6),
         species = case_when(substr(id, 1, 4) == "ACER" ~ "A. cervicornis",
                             substr(id, 1, 4) == "APRO" ~ "A. prolifera",
                             substr(id, 1, 4) == "APAL" ~ "A. palmata"),
         date = ymd(date)) %>%
  filter(!is.na(date)) %>%
  select(date, site, species, genotype, id, n_frags, n_colonies)

outplant_monitoring <- read_excel(here("restoration_monitoring", "data_raw", "genotype tracking.xlsx"), sheet = "outplant monitoring") %>% 
  clean_names() %>%
  filter(!is.na(colonies_live)) %>% # filtering out any genotypes with missing data
  filter(id != "APAL29.2") %>% # removing mysterious APAL29.2
  mutate(genotype = substr(id, 1, 6),
         colonies_planted = as.numeric(colonies_planted),
         date_monitored = ymd(date_monitored),
         date_planted = ymd(date_planted))
```
Nursery monitoring data

```{r}
nursery_mon <- read_excel(here("restoration_monitoring", "data_raw", "Genotype tracking.xlsx"), sheet = "nursery monitoring") %>% 
  clean_names() %>%
  mutate(date = ymd(date),
         species = case_when(substr(genotype, 1, 4) == "ACER" ~ "A. cervicornis",
                             substr(genotype, 1, 4) == "APRO" ~ "A. prolifera",
                             substr(genotype, 1, 4) == "APAL" ~ "A. palmata",
                             substr(genotype, 1, 4) == "PFUR" ~ "P. furcata",
                             substr(genotype, 1, 4) == "OANN" ~ "O. annularis"),
         ) %>%
  filter(!is.na(date)) %>%
  mutate_at(c('n_healthy', 'n_dead', 'n_bleached', 'n_pale', 'n_diseased', 'n_other'), ~replace_na(.,0))

frag_status <- read.csv(here("restoration_monitoring", "data_outputs", "frag_status.csv"))
disease <- read.csv(here("restoration_monitoring", "data_outputs", "disease.csv"))
thermtol_2023 <- read.csv(here("restoration_monitoring", "data_outputs", "thermtol_2023.csv"))
```

Integrating information by genotype

```{r}
# merging into one with all information per genotype

genotype_tracking <- collection %>%
  select(genotype, collection_date = date, collection_site, collection_lat, collection_lon) %>%
  left_join(nursery_locations) %>%
  left_join(frag_status %>% 
              select(genotype, n_frags_nurseries = n_tot_alive)) %>%
  # left_join(thermtol_2023) %>%
  # left_join(disease) %>%
  # left_join(outplant_monitoring %>%
  #             group_by(genotype, site) %>%
  #             summarise(colonies_live = sum(colonies_live)) %>%
  #             mutate(site = case_when(site == "York Island" ~ "york_colonies",
  #                                     site == "Ten Pound Bay" ~ "tpb_colonies",
  #                                     site == "Ricketts" ~ "ricketts_colonies")) %>%
  #             pivot_wider(names_from = site, values_from = colonies_live) %>%
  #             mutate(outplant_colonies = ricketts_colonies + tpb_colonies + york_colonies) %>% # live colonies
  #             select(genotype, outplant_colonies, york_colonies, tpb_colonies, ricketts_colonies)) %>%
  # left_join(outplant_monitoring %>%
  #             pivot_longer(
  #                cols = starts_with("live_c"),
  #                names_to = "colony",
  #                names_prefix = "live_c",
  #                values_to = "survivorship",
  #                values_drop_na = TRUE #  drops all colonies planted as indv (APALs and some APROs)
  #             ) %>%
  #             group_by(genotype, id) %>%
  #             summarise(survivorship_col = mean(survivorship)) %>%
  #             right_join(outplant_monitoring %>%
  #                          select(date_monitored, site, genotype, id, date_planted, colonies_planted, colonies_live),
  #                        by = c("genotype", "id")) %>%
  #             mutate(survivorship_col = if_else(is.na(survivorship_col), 100, survivorship_col),
  #                    survivorship_pop = survivorship_col * colonies_live / colonies_planted) %>%
  #             relocate(survivorship_col, .before = survivorship_pop) %>%
  #             group_by(genotype) %>%
  #             summarise(survivorship = round(mean(survivorship_pop), 2),
  #                       se = round(sd(survivorship_pop)/sqrt(n()), 2))) %>%
  mutate_at(c('york_locations', 'tpb_locations', 'cades_locations', 'gb_locations', 'lab'), ~replace_na(.,"")) %>%
  mutate_at(c('n_ropes', 'n_trees', 'n_frags_nurseries'), ~replace_na(.,0)) %>% # , 'outplant_colonies', 'york_colonies', 'tpb_colonies', 'ricketts_colonies'
  arrange(genotype) %>%
  mutate(active = case_when((york_locations == "") & (tpb_locations == "") & (cades_locations == "") & (gb_locations == "") ~ "N",
         .default = "Y")) %>%
  mutate(productive = case_when((york_locations == "") & (tpb_locations == "") & (cades_locations == "") ~ "N",
         .default = "Y")) %>%
  select(genotype, active, productive, collection_date, collection_site, collection_lat, collection_lon, york_locations, tpb_locations, cades_locations, gb_locations, lab, n_frags_nurseries) # removing outplant results for now until we start outplanting again

write.csv(genotype_tracking, here("restoration_monitoring", "data_outputs", "genotype_tracking.csv"), row.names=FALSE)
```

Summary data

```{r, eval = F}

# determine most recent monitoring dates for Cades and Nonsuch to get latest data
last_mon_cades <- nursery_mon %>%
  filter(nursery == "Cades") %>%
  filter(date == last(date))
last_mon_date_cades <- last_mon_cades$date

last_mon_nonsuch <- nursery_mon %>%
  filter(nursery == "York") %>%
  filter(date == last(date))
last_mon_date_nonsuch <- last_mon_nonsuch$date

# summarize number of genotypes and fragments by species
summary_spp <- genotype_tracking %>%
  mutate(species = substr(genotype, 1, 4)) %>%
  filter(active == "Y") %>%
  group_by(species) %>%
  summarize(n_genotypes_active = n()) %>%
  left_join(genotype_tracking %>%
              mutate(species = substr(genotype, 1, 4)) %>%
              filter(productive == "Y") %>%
              group_by(species) %>%
              summarize(n_genotypes_productive = n())
            ) %>%
  mutate_at(c('n_genotypes_active', 'n_genotypes_productive'), ~replace_na(.,0)) %>%
  left_join(nursery_mon %>% 
              filter(date %in% c(last_mon_cades$date, last_mon_nonsuch$date)) %>% # most recent date
              mutate(species = substr(genotype, 1, 4)) %>%
              select(species, n_healthy, n_diseased, n_bleached, n_pale, n_other) %>%
              pivot_longer(cols = n_healthy:n_other, 
                           names_to = "condition", values_to = "n_frags") %>%
              group_by(species) %>%
              summarize(n_frags = sum(n_frags))
            )

summary <- summary_spp %>%
  summarize(n_genotypes_active = sum(n_genotypes_active),
            n_genotypes_productive = sum(n_genotypes_productive),
            n_frags = sum(n_frags)) %>%
  mutate(species = "Total") %>%
  select(species, n_genotypes_active, n_genotypes_productive, n_frags) %>%
  rbind(summary_spp)

write.csv(summary, here("restoration_monitoring", "data_outputs", "summary.csv"), row.names=FALSE)


# interval summaries
# q3 <- interval(ymd("2024-01-01"), ymd("2024-03-31"))
# n_genotypes_active_q3 <- collection %>%
#   filter(date %within% q3) %>%
#   select(genotype) %>%
#   left_join(nursery_mon %>% 
#               filter(date == "2024-03-25") %>%
#               mutate(n_tot = n_healthy + n_diseased + n_bleached + n_pale) %>%
#               select(genotype, n_tot)) # last monitoring date in Q3
# 
# q3_genotypes <- q3_additions %>% 
#   select(genotype) %>%
#   distinct()
```




