---
title: "Outplant monitoring"
author: "Molly Wilson"
date: "2023-02-19"
output: 
  html_document:
    code_folding: hide
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(janitor)
library(snakecase) # for adjusting capitalization of text within data (e.g., species names)
library(knitr) # for including tables
library(stringr)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

## Outplant statistics
```{r}
outplants <- read_excel(here("restoration_monitoring", "data", "Genotype monitoring master.xlsx"), sheet = "Outplants") %>% 
  clean_names() %>%
  mutate(genotype = substr(id, 1, 6),
         species = case_when(substr(id, 1, 4) == "ACER" ~ "A. cervicornis",
                             substr(id, 1, 4) == "APRO" ~ "A. prolifera",
                             substr(id, 1, 4) == "APAL" ~ "A. palmata")) %>%
  filter(!is.na(date)) %>%
  select(date, site, species, genotype, id, n_frags, n_colonies)

frags_tot <- sum(outplants$n_frags)
colonies_tot <- sum(outplants$n_colonies)
genotypes_tot <- count(outplants %>%
  distinct(genotype))
genotypes_spp_site <- outplants %>%
  group_by(species, site) %>%
  distinct(genotype) %>%
  count()
```

Total number of fragments planted: **`r frags_tot`**

Total number of colonies planted: **`r colonies_tot`**

Total number of genotypes planted: **`r genotypes_tot`**

Genotypes planted by species and site:
`r kable(genotypes_spp_site)`

## Survivorship (Feb. 2023)
```{r}
outplant_monitoring <- read_excel(here("restoration_monitoring", "data", "genotype monitoring master.xlsx"), sheet = "Outplant monitoring") %>% 
  clean_names() %>%
  filter(!is.na(colonies_live)) %>% # filtering out any genotypes with missing data
  filter(id != "APAL29.2") %>% # removing mysterious APAL29.2
  mutate(colonies_planted = as.numeric(colonies_planted))

survivorship_id <- outplant_monitoring %>%
  pivot_longer(
     cols = starts_with("live_c"),
     names_to = "colony",
     names_prefix = "live_c",
     values_to = "survivorship",
     values_drop_na = TRUE #  drops all colonies planted as indv (APALs and some APROs)
  ) %>%
  group_by(date, id) %>%
  summarise(survivorship_col = mean(survivorship)) %>%
  right_join(outplant_monitoring %>%
               select(date, site, id, colonies_planted, colonies_live), by = c("date", "id")) %>%
  mutate(survivorship_col = if_else(is.na(survivorship_col), 100, survivorship_col),
         survivorship_pop = survivorship_col * colonies_live / colonies_planted) %>%
  relocate(survivorship_col, .before = survivorship_pop) %>%
  mutate(genotype = substr(id, 1, 6),
         species = case_when(substr(id, 1, 4) == "ACER" ~ "A. cervicornis",
                             substr(id, 1, 4) == "APRO" ~ "A. prolifera",
                             substr(id, 1, 4) == "APAL" ~ "A. palmata"),
         site = case_when(site == "York Island" ~ "York",
                             site == "Ten Pound Bay" ~ "Ten Pound",
                             site == "Ricketts" ~ "Ricketts"))
```

### Survivorship by genotype
```{r}
survivorship_genotype <- survivorship_id %>%
  group_by(species, genotype) %>%
  summarise(survivorship = mean(survivorship_pop),
            se = sd(survivorship_pop)/sqrt(n()),
            replicates = n())

ggplot(survivorship_genotype %>% filter(species == "A. palmata"), aes(x = reorder(genotype, -survivorship), y = survivorship)) +
  geom_col(color = "black", fill = "slategray", alpha = 0.9) +
  geom_errorbar(aes(ymin = survivorship - se, ymax = survivorship + se), width = .2,
                 position = position_dodge(.9)) +
  lims(y = c(0,100)) +
  labs(y = "Percent survival", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(survivorship_genotype %>% filter(species == "A. prolifera"), aes(x = reorder(genotype, -survivorship), y = survivorship)) +
  geom_col(color = "black", fill = "slategray", alpha = 0.9) +
  geom_errorbar(aes(ymin = survivorship - se, ymax = survivorship + se), width = .2,
                 position = position_dodge(.9)) +
  lims(y = c(0,100)) +
  labs(y = "Percent survival", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(survivorship_genotype %>% filter(species == "A. cervicornis"), aes(x = reorder(genotype, -survivorship), y = survivorship)) +
  geom_col(color = "black", fill = "slategray", alpha = 0.9) +
  geom_errorbar(aes(ymin = survivorship - se, ymax = survivorship + se), width = .2,
                 position = position_dodge(.9)) +
  lims(y = c(0,100)) +
  labs(y = "Percent survival", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

### Survivorship by species
```{r}
survivorship_spp <- survivorship_id %>%
  group_by(species) %>%
  summarise(survivorship = mean(survivorship_pop),
            se = sd(survivorship_pop)/sqrt(n()),
            replicates = n())

ggplot(survivorship_spp, aes(x = species, y = survivorship)) +
  geom_col(color = "black", fill = "slategray", alpha = 0.9) +
  geom_errorbar(aes(ymin = survivorship - se, ymax = survivorship + se), width = .2,
                 position = position_dodge(.9)) +
  lims(y = c(0,100)) +
  labs(y = "Percent survival", x = "") +
  theme_bw() +
  theme(strip.text = element_text(face = "italic"))

survivorship_spp_site <- survivorship_id %>%
  group_by(species, site) %>%
  summarise(survivorship = mean(survivorship_pop),
            se = sd(survivorship_pop)/sqrt(n()),
            replicates = n())

ggplot(survivorship_spp_site, aes(x = site, y = survivorship)) +
  geom_col(color = "black", fill = "slategray", alpha = 0.9) +
  facet_grid(. ~ species) +
  geom_errorbar(aes(ymin = survivorship - se, ymax = survivorship + se), width = .2,
                 position = position_dodge(.9)) +
  lims(y = c(0,100)) +
  labs(y = "Percent survival", x = "") +
  theme_bw() +
  theme(strip.text = element_text(face = "italic"))
```



