---
title: "Apprill sample collection"
author: "Molly Wilson"
date: "2024-09-14"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(here) # for accessing files with directory
library(readxl) # for reading indv. sheets within excel files
library(janitor) # for cleaning variable names so they have consistent capitalization etc.
library(lubridate) # for converting date formats
library(gginnards) # for reordering layers within ggplots
library(sf)
library(ggmap)
library(ggspatial)

knitr::opts_chunk$set(message = FALSE, warning = FALSE) # this sets the preferences for each code chunk so that errors/messages/warnings don't get displayed in the knit rmarkdown
`%nin%` <- negate(`%in%`) # creating 'not in' function for general use
```

```{r}
data_seawater <- read_excel(here("water_quality", "data_raw", "Apprill 2024 samples.xlsx"), sheet = "Seawater data") %>% 
  clean_names() %>%
  filter(toc != "no sample taken") %>%
  mutate_at(c('toc', 'tn'), as.numeric)

flpoint_site <- function(data_wq, y, ylab, ymin, ymax) {
  ggplot() +
    geom_point(data = data_wq, 
             aes(reorder(site, {{y}}), {{y}}),
             alpha = 0.6) +
    labs(x = "", y = ylab) +
    ylim(ymin, ymax) +
    theme_bw() +
    coord_flip()
}

plot_dim_w = 4
plot_dim_h = 4

toc_point <- flpoint_site(data_seawater, toc, "Total Organic Carbon", 0, 125)
ggsave(here("water_quality", "figs", "2023-2024", "toc.png"),  width = plot_dim_w, height = plot_dim_h)

tn_point <- flpoint_site(data_seawater, tn, "Total Nitrogen", 0, 10)
ggsave(here("water_quality", "figs", "2023-2024", "tn.png"),  width = plot_dim_w, height = plot_dim_h)
```

