---
title: "Kor Cleaning"
author: "Molly Wilson"
date: "2026-01-16"
output: html_document
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(readr)
library(janitor)
library(scales)
library(lubridate)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

Notes

- currently an issue with Jan file - creates character date, using previously generated historical .csv for now

```{r}
file_raw <- here("water_quality", "data_raw", "Kor Measurement File Export - Apr 2026.csv")
file_clean <- here("water_quality", "data_outputs", "kor_exports", "ysi_clean_apr2026.csv")

# 1. determine encoding of new file from Kor exports
encoding <- guess_encoding(file_raw)

# 2. import raw YSI data depending on encoding

## 2a. non-UTF encoded files
# raw <- read_csv(file_raw,
#   col_names = FALSE,
#   show_col_types = FALSE) %>%
#   filter(!str_detect(X1, "MEAN VALUE|STANDARD DEVIATION|SENSOR SERIAL NUMBER"))

## 2b. UTF encoded files
lines <- read_lines(
  file_raw,
  locale = locale(encoding = "UTF-16LE")
)
raw <- str_split(lines, ",", simplify = TRUE) %>%
  as_tibble(.name_repair = ~ paste0("X", seq_along(.)))


# 3. import list of entries to be omitted
omissions <- read_excel(here("water_quality", "data_raw", "Water quality data.xlsx"), sheet = "ysi omissions") %>%
  mutate(time = format(time, "%H:%M:%S"),
         date = as.Date(date))
### need to reformat date/times?

# 4. import list of entries to be corrected
corrections <- read_excel(here("water_quality", "data_raw", "Water quality data.xlsx"), sheet = "ysi corrections") %>%
  mutate(time = format(time, "%H:%M:%S"),
         date = as.Date(date))
```

Cleaning YSI/Kor .csv
```{r}
# identify header rows for each sensor type
header_rows_turbidity <- which(apply(raw, 1, function(row)
  any(str_detect(as.character(row), "TURBIDITY FNU"))
))

header_rows_gen <- which(apply(raw, 1, function(row)
  any(str_detect(as.character(row), "TAL PE RFU"))
))

# identify data rows for each sensor type
data_rows_turbidity <- header_rows_turbidity + 1
data_rows_gen       <- header_rows_gen + 1

# function for cleaning data into one tibble per sensor
clean_sensor <- function(header_rows, data_rows, raw_df) {

  blocks <- map2(header_rows, data_rows, ~{

    header <- as.character(unlist(raw_df[.x, ]))
    header <- iconv(header, from = "", to = "UTF-8", sub = "")

    empty_idx <- which(is.na(header) | header == "")
    header[empty_idx] <- paste0("empty_col_", seq_along(empty_idx))

    header <- make.names(header, unique = TRUE)
    header <- make_clean_names(header)

    data <- as.character(unlist(raw_df[.y, ]))

    df <- as_tibble(as.list(data), .name_repair = "minimal")
    colnames(df) <- header

    df
  })

  tidy_df <- bind_rows(blocks) %>%
    mutate(across(everything(), ~ type.convert(., as.is = TRUE))) %>%
    mutate(
      date = as.Date(date_m_d_yyyy, format = "%m/%d/%Y"),
      time = format(
        lubridate::parse_date_time(time_h_mm_ss_tt, orders = "I:M:S p"),
        "%H:%M:%S"
      )
    )
    # mutate(date = as.Date(date_m_d_yyyy, format = "%m/%d/%y"),
    #        time = format(
    #          lubridate::parse_date_time(time_h_mm_ss_tt, orders = "I:M:S p"),
    #          "%H:%M:%S"))

  tidy_df
}

# creating clean dfs for turbidity and general sensor data
turbidity <- clean_sensor(header_rows_turbidity, data_rows_turbidity, raw) %>%
  select(date, time, site_code_depth = site_name, turbidity_fnu) %>%
  anti_join(omissions, by = c("date", "time", "site_code_depth")) %>%
  left_join(corrections, by = c("date", "time", "site_code_depth")) %>%
  mutate(site_code_depth = coalesce(site_corrected, site_code_depth)) %>%
  select(-site_corrected)

general <- clean_sensor(header_rows_gen, data_rows_gen, raw) %>%
  select(date, time, site_code_depth = site_name, tal_pe_rfu, chlorophyll_rfu, 
         # accounting for alternative conductivity names per encoding type
         cond_us_cm = any_of(c("cond_m_s_cm", "cond_s_cm", "cond_m_us_cm")),
         spcond_us_cm = any_of(c("spcond_m_s_cm", "spcond_s_cm", "spcond_m_us_cm")),
         tds_mg_l, sal_psu, odo_mg_l, ph, temp_c) %>%
  anti_join(omissions, by = c("date", "time", "site_code_depth")) %>%
  left_join(corrections, by = c("date", "time", "site_code_depth")) %>%
  mutate(site_code_depth = coalesce(site_corrected, site_code_depth)) %>%
  select(-site_corrected)

# checking that corrections were applied (should be 0 obs.)
chk_turbidity <- turbidity %>%
  inner_join(corrections %>% select(date, time), 
             by = c("date", "time"))
chk_general <- general %>%
  inner_join(corrections %>% select(date, time), 
             by = c("date", "time"))

# creating one df with both sensor groups
ysi <- general %>%
  select(-time) %>%
  full_join(turbidity %>%
              select(-time),
            by = c("date", "site_code_depth")) %>%
  mutate(site_code_depth = case_when(site_code_depth == "Corington" ~ "COV",
                                     site_code_depth == "greenhEB" ~ "GEB",
                                     site_code_depth == "SH1" ~ "SRS1",
                                     TRUE ~ toupper(site_code_depth)),
         site_code = str_extract_all(site_code_depth, "[A-Za-z]") %>% 
           sapply(paste0, collapse = ""),
         depth = str_extract_all(site_code_depth, "\\d") %>% 
           sapply(paste0, collapse = "") %>% 
           as.integer(),
         depth = coalesce(depth, 1)) %>% # replacing sites with no depth as depth = 1
  relocate(date, site_code_depth, site_code, depth) %>%
  rename(do_mg_l = odo_mg_l) %>%
  set_names(~ str_replace_all(., "_s_", "_us_")) # replacing any "u" symbol lost when stripping data

# checking for duplicated/incomplete data (should be 0 obs.)
chk_ysi1 <- ysi %>% 
  group_by(site_code_depth, date) %>%
  summarize(count = n()) %>%
  filter(count != 1)
chk_ysi2 <- ysi %>%
  filter(is.na(tal_pe_rfu) | is.na(turbidity_fnu))

# export csv and clean env.
write_csv(ysi, file_clean)
rm(list = ls(pattern = "^chk"))
```



