---
title: "WQ4"
author: "Molly Wilson"
date: '2022-09-14'
output: html_document
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) # for accessing files with directory
library(readxl) # for reading indv. sheets within excel files
library(janitor) # for cleaning variable names so they have consistent capitalization etc.
library(lubridate) # for converting date formats
library(zoo) # for converting date formats

library(knitr) # for including tables
library(ggpubr) # for printing multiple plots together

knitr::opts_chunk$set(message = FALSE, warning = FALSE) # this sets the preferences for each code chunk so that errors/messages/warnings don't get displayed in the knit rmarkdown
```

```{r}
samples <- read_excel(here("water_quality", "data", "samples.xlsx"), sheet = "raw_data") %>%  
  clean_names() %>%
  filter(id != c("E1", "E2")) %>%
  select(-nitrate_raw, -phosphate_raw) %>%
  mutate(date = as.character(date),
         month = month(ymd(date), label = TRUE),
         year = year(ymd(date)),
         date_label = paste(as.character(month), as.character(year)),
         salinity = salinity/1000, # ppm -> ppt
         tds = tds/1000, # ppm -> ppt
         enterococci = as.numeric(replace(enterococci, enterococci == "ND", 0)),
         row = row_number()) %>%
  left_join(read_excel(here("water_quality", "data", "samples.xlsx"), sheet = "sites") %>%
  clean_names(), by = "id") %>%
  unite(id_site, id, site, sep = " (", remove = F) %>%
  mutate(id_site = paste0(id_site, ")"),
         date_cat = case_when(date == "2022-09-06" ~ "September 2022",
                              date %in% c("2021-08-11") ~ "Previous summer samples",
                              date %in% c("2021-04-06", "2022-04-07") ~ "Previous winter samples"),
         date_cat2 = if_else(date == "2022-09-06", "September 2022", "Previous samples"))
```

WQ1-WQ4 trends
```{r}
c_range <- "slategray1"
shapes_dates <- c(1, 2, 16)
colors_dates <- c("springgreen4", "turquoise4", "black")

# pH: 7.7 and 8.5 units  (EPMA, 2019)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 7.7, ymax = 8.5)
ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.2) +
  scale_fill_manual(values = c_range, name = "Target range", labels = c("EPMA 2019")) +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = ph, shape = date_cat, alpha = date_cat, color = type)) +
  scale_shape_manual(name = "Sample date", values = shapes_dates) +
  scale_color_manual(name = "Site type", labels = c("Control", "Nursery", "Treatment"), values = colors_dates) +
  scale_alpha_manual(name = "Sample date", values = c(0.3, 0.3, 1)) +
  labs(x = "", y = "pH") +
  ylim(5, 9) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "pH.png"), width = 6, height = 4)

# TDS
ggplot() +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = tds, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "TDS") +
  ylim(30, 60) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "tds.png"), width = 6, height = 4)

# Salinity: 32,000 to 42,000 ppm (NOAA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 32, ymax = 42)
ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, name = "Target range", labels = c("NOAA 2021")) +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = salinity, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "Salinity") +
  ylim(25, 50) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "salinity.png"), width = 6, height = 4)

# Turbidity (no reference)
ggplot() +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = turbidity, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "Turbidity (NTU)") +
  ylim(0, 5) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "turbidity.png"), width = 6, height = 4)


# DO: Must be greater than 6.0 ppm  (EPMA, 2019)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 6, ymax = Inf)
ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, name = "Target range", labels = c("EPMA 2019")) +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = do, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "Dissolved oxygen (ppm)") +
  ylim(0, 12) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "do.png"), width = 6, height = 4)

# Nitrates (no reference)
ggplot() +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = nitrate, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "Nitrate (ppm)") +
  ylim(0, 0.2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "nitrate.png"), width = 6, height = 4)

# Phosphates (no reference)
ggplot() +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = phosphate, shape = date)) +
  scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = "Phosphate (ppm)") +
  ylim(0, 0.6) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "phosphate.png"), width = 6, height = 4)

# Temperature: 23°–29.6°Celsius (NOAA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 23, ymax = 29.6)
ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, name = "Target range", labels = c("NOAA 2021")) +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = temperature, shape = date)) +
   scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = expression("Temperature ("*~degree*C*")")) +
  ylim(18, 32) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "temperature.png"), width = 6, height = 4)

# Conductivity (no reference)
ggplot() +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = conductivity, shape = date)) +
   scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = expression("Conductivity ("*mu*S*" "*cm^-1*")")) +
  ylim(50000, 60000) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "conductivity.png"), width = 6, height = 4)

# Enterococci (below 33, EPMA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 0, ymax = 33)
ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, name = "Target range", labels = c("EPMA 2019")) +
  geom_point(data = filter(samples, !str_detect(id, "^S")), aes(x = id, y = enterococci, shape = date)) +
   scale_shape_manual(name = "Sample date", labels = labels_dates, values = shapes_dates) +
  labs(x = "", y = expression("Enterococci (cfu 100"*ml^-1*")")) +
  ylim(0, 35) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "enterococci.png"), width = 6, height = 4)
```

Means and SE
```{r}
summary <- samples %>%
  filter(!str_detect(id, "^S")) %>%
  select(-c(id, type, site)) %>%
  mutate(enterococci = as.numeric(enterococci)) %>%
  pivot_longer(-c(id_site, date), names_to = "metric", values_to = "value") %>%
  group_by(metric, date) %>%
  summarise(n = n(),
            mean = mean(value),
            sd = sd(value),
            se = sd/sqrt(n))
```

Summary figure
```{r}
c_range <- "slategray1"

# pH: 7.7 and 8.5 units  (EPMA, 2019)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 7.7, ymax = 8.5)
ph <- ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, guide = "none") +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = ph), alpha = 0) +
  labs(x = "", y = "pH") +
  ylim(5, 9) +
  theme_bw()

# TDS
tds <- ggplot() +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = tds), alpha = 0) +
  labs(x = "", y = "TDS") +
  ylim(30, 60) +
  theme_bw()

# Salinity: 32,000 to 42,000 ppm (NOAA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 32, ymax = 42)
salinity <- ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, guide = "none") +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = tds), alpha = 0) +
  labs(x = "", y = "Salinity") +
  ylim(25, 50) +
  theme_bw()

# Turbidity (no reference)
turbidity <- ggplot() +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = turbidity), alpha = 0) +
  labs(x = "", y = "Turbidity (NTU)") +
  ylim(0, 5) +
  theme_bw()


# DO: Must be greater than 6.0 ppm  (EPMA, 2019)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 6, ymax = Inf)
do <- ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, guide = "none") +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = do), alpha = 0) +
  labs(x = "", y = "Dissolved oxygen (ppm)") +
  ylim(0, 12) +
  theme_bw() 

# Nitrates (no reference)
nitrates <- ggplot() +
  geom_boxplot(data = samples, aes(x = date, y = nitrate), alpha = 0) +
  labs(x = "", y = "Nitrate (ppm)") +
  ylim(0, 0.2) +
  theme_bw()

# Phosphates (no reference)
phosphates <- ggplot() +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = phosphate, group = date), alpha = 0) +
  labs(x = "", y = "Phosphate (ppm)") +
  ylim(0, 0.6) +
  theme_bw()

# Temperature: 23°–29.6°Celsius (NOAA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 23, ymax = 29.6)
temperature <- ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, guide = "none") +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = temperature), alpha = 0) +
  labs(x = "", y = expression("Temperature ("*~degree*C*")")) +
  ylim(18, 32) +
  theme_bw()


# Conductivity (no reference)
conductivity <- ggplot() +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = conductivity), alpha = 0) +
  labs(x = "", y = expression("Conductivity ("*mu*S*" "*cm^-1*")")) +
  ylim(30000, 60000) +
  theme_bw()

# Enterococci (below 33, EPMA)
rect_dat = data.frame(xmin = -Inf, xmax = Inf, ymin = 0, ymax = 33)
enterococci <- ggplot() +
  geom_rect(data = rect_dat, 
              aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax, fill = "What"),
              alpha = 0.3) +
  scale_fill_manual(values = c_range, guide = "none") +
  geom_boxplot(data = samples, aes(x = reorder(date_label, row), y = enterococci), alpha = 0) +
  labs(x = "", y = expression("Enterococci (cfu 100"*ml^-1*")")) +
  ylim(0, 35) +
  theme_bw() 

```

```{r}
ggarrange(ph, do, tds, turbidity, nitrates, phosphates, temperature, enterococci, salinity, conductivity, 
          ncol = 2, nrow = 5)
ggsave(here("water_quality", "figs", "WQ4", "summary.png"), width = 6, height = 12)
```


Sargassum
```{r}
sarg_colors <- c("firebrick3", "darkorange2", "goldenrod1", "slategray3", "cyan4")
sargassum <- samples %>%
  filter(date == "2022-09-06" & str_detect(id, "^S|^C|^N")) %>%
  mutate(category = case_when(id %in% c("C1", "C2") ~ "Controls",
                              id %in% c("N1", "N2") ~ "Nurseries",
                              id %in% c("S1", "S4") ~ "Mat center",
                              id %in% c("S2", "S5") ~ "Mat edge",
                              id %in% c("S3", "S6") ~ "200m from edge")) %>%
  mutate(id = factor(id, levels = c("S1", "S4", "S2", "S5", "S3", "S6", "C1", "C2", "N1", "N2"))) %>%
  mutate(category = factor(category, levels = c("Mat center", "Mat edge", "200m from edge", "Controls", "Nurseries")))

# pH:
ph <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = ph, color = category, group = category), size = 3) +
  labs(x = "", y = "pH") +
  scale_color_manual(values = sarg_colors, name = "") +
  ylim(5, 9) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_pH.png"), width = 6, height = 4)

# TDS
tds <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = tds, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "TDS") +
  ylim(30, 60) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_tds.png"), width = 6, height = 4)

# Salinity: 32,000 to 42,000 ppm (NOAA)
salinity <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = salinity, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "Salinity") +
  ylim(25, 50) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_salinity.png"), width = 6, height = 4)

# Turbidity
turbidity <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = turbidity, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "Turbidity (NTU)") +
  ylim(0, 30) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_turbidity.png"), width = 6, height = 4)

# DO: Must be greater than 6.0 ppm  (EPMA, 2019)
do <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = do, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "DO (ppm)") +
  ylim(0, 12) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_do.png"), width = 6, height = 4)

# Nitrates (no reference)
nitrates <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = nitrate, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "Nitrate (ppm)") +
  ylim(0, 0.2) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_nitrate.png"), width = 6, height = 4)

# Phosphates (no reference)
phosphates <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = phosphate, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = "Phosphate (ppm)") +
  ylim(0, 0.6) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_phosphate.png"), width = 6, height = 4)

# Temperature: 23°–29.6°Celsius (NOAA)
temperature <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = temperature, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = expression("Temperature ("*~degree*C*")")) +
  ylim(18, 32) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_temperature.png"), width = 6, height = 4)

# Conductivity (no reference)
conductivity <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = conductivity, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = expression("Conductivity ("*mu*S*" "*cm^-1*")")) +
  ylim(30000, 60000) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_conductivity.png"), width = 6, height = 4)

# Enterococci
enterococci <- ggplot() +
  geom_point(data = sargassum, aes(x = id, y = enterococci, color = category, group = category), size = 3) +
  scale_color_manual(values = sarg_colors, name = "") +
  labs(x = "", y = expression("Enterococci (cfu 100"*ml^-1*")")) +
  ylim(0, 35) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("water_quality", "figs", "WQ4", "sarg_enterococci.png"), width = 6, height = 4)
```

```{r, fig.width = 4, fig.height = 8}
ggarrange(ph, do, tds, turbidity, nitrates, phosphates, temperature, enterococci, salinity, conductivity, 
          ncol = 2, nrow = 5, common.legend = TRUE, legend = "top")
ggsave(here("water_quality", "figs", "WQ4", "sargassum.png"), width = 6, height = 12)
```


