---
title: "Water quality testing"
author: "Molly Wilson"
date: "2026-01-01"
output: 
  html_document:
    toc: true
    code_folding: hide
    number_sections: false
    theme: cerulean
    highlight: haddock
---

```{r}
sites <- read_excel(here("water_quality", "data_raw", "Water quality data.xlsx"), sheet = "sites") %>% 
  clean_names()

ysi_raw <- read_excel(here("water_quality", "data_raw", "Water quality data.xlsx"), sheet = "ysi") %>% 
  rename_with(tolower) %>% # prevents clean_names() from adding extra underscores before caps
  clean_names() %>%
  rename(site_code_depth = site_code)

ysi_dup <- ysi_raw %>% group_by(site_code_depth, date) %>%
  summarize(count = n()) %>%
  filter(count >2) # should be only 2 samples (1 per probe) at each site/depth per day

ysi <- ysi_raw %>%
  select(date, site_code_depth, temperature_c = temperature_c_24, ph, do_mg_l, do_percent_sat, conductivity_us_cm, sal_psu, phycoerythrin_rfu, chlorophyll_rfu) %>%
  drop_na() %>%
  left_join(ysi_raw %>%
              select(date, site_code_depth, turbidity_fnu) %>%
              drop_na(),
            by = c("date", "site_code_depth")) %>%
  mutate(site_code = str_replace(site_code_depth, "[:digit:]", ""),
         depth_m = parse_number(site_code_depth),
         depth_m = replace_na(depth_m, 1)) # surface-only sites are assumed to be approx 1m

```
# Archive

```{r}
         # mutate(
#date_adj = if_else(day(date) > 25, date %m+% months(1), date),
         #monitoring_month = floor_date(date_adj, unit = "month"),
         #month_label = format(monitoring_month, "%b %Y")
# )
```

