---
title: "MMA Reef"
author: "Molly Wilson"
date: "6/22/2022"
output: 
  html_document:
    code_folding: hide
---

# {.tabset}

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(janitor)
library(snakecase) # for adjusting capitalization of text within data (e.g., species names)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

# Benthic

```{r}
# import and clean data

rf_benthic <- read_excel(here("mma", "data", "mma_coral_benthic.xlsx"), sheet = "benthic") %>%  
  clean_names() %>%
  filter(!is.na(site)) %>% # remove any incomplete rows at the end of the data
  # separate(species_code, c("species_code", "indicator")) %>% # separating variables with an underscore into two columns
  mutate(species = to_any_case(species, case = "sentence"), # this makes sure species names are correctly capitalized
         site = to_any_case(site, case = "title"),
         # consolidating categories here for graphs:
         cat_c = case_when(category_code %in% c("LC", "SLC") ~ "Hard corals",
                                  category_code %in% c("MA") ~ "Macroalgae",
                                  category_code %in% c("TA") ~ "Turf algae",
                                  category_code %in% c("CCA", "CCA_ND") ~ "CCA",
                                  category_code %in% c("OINV", "SPON", "AINV", "CYAN", "PEY") ~ "Other competitors",
                                  category_code %in% c("SAND", "HOLE", "SG", "PAVE") ~ "Other substratum"
                                    ),
         # adding algal type for graphs about palatability:
         algal_type = case_when(type_code %in% c("BFMA", "GFMA", "RFMA") ~ "Fleshy macroalgae",
                                type_code %in% c("GCMA", "RCMA") ~ "Calcareous macroalgae",
                                type_code %in% c("TA", "TAS", "STA") ~ "Turf algae"),
         # certain substrates are not suitable for coral or algal growth, so should not detract from percent cover
         av_sub_yn = if_else(category_code %in% c("SAND", "HOLE", "SG", "PAVE"), "no", "yes")
         ) %>%
    filter(!is.na(cat_c) & !is.na(species)) # need GRB to fix some data errors, but using this for now
```

Percent cover by site and category
* Maybe we should make pie charts again for these?

```{r}
# "expand" dataframe so that it contains all benthic categories per site/transect/meter -> join full dataset so that any meters where a species was absent it will show up as 0 (as opposed to having no entry)
rf_pc_cat_m <- rf_benthic %>%
  filter(av_sub_yn == "yes") %>% # percent cover is relative to available substrate
  expand(nesting(site, transect, meter), cat_c) %>%
  # this is where we add in our actual data to this expanded template:
  left_join(rf_benthic %>% 
              filter(av_sub_yn == "yes") %>% # only looking at what is considered available substrate (no sand, etc.)
              group_by(site, transect, meter) %>%
              mutate(n_pts = n()) %>% # showing total number of points per meter that are considered available substrate
              ungroup() %>%
              group_by(site, transect, meter, n_pts, cat_c) %>%
              summarize(pc_m = 100*n()/n_pts) %>% # n() counts the number of entries within a given group
              ungroup() %>%
              distinct() %>%
              select(-n_pts), 
            by = c("site", "transect", "meter", "cat_c")) %>%
  mutate(pc_m = if_else(is.na(pc_m), 0, pc_m))

# average these meter-level results within transect, then within sites
rf_pc_cat_site <- rf_pc_cat_m %>%
  group_by(site, transect, cat_c) %>%
  summarize(pc_t = mean(pc_m)) %>%
  ungroup() %>%
  group_by(site, cat_c) %>%
  summarize(n_test = n(),
            pc_mean = mean(pc_t),
            pc_se = sd(pc_t)/sqrt(n())
            ) %>%
  filter(cat_c != "Other substratum") %>% 
  mutate(cat_c = factor(cat_c, levels = c("Hard corals", "CCA", "Macroalgae", "Turf algae", "Other competitors")))

# quick check to make sure everything adds up to 100% at the meter and site level
test1 <- rf_pc_cat_m %>%
  group_by(site, transect, meter) %>%
  summarize(total = sum(pc_m))
test2 <- rf_pc_cat_site %>%
  group_by(site) %>%
  summarize(total = sum(pc_mean))

# graphs
ggplot(rf_pc_cat_site, 
       aes(x = cat_c, y = pc_mean)) +
  geom_col(fill = "blue") +
  facet_grid(. ~ site) +
  labs(y = "Mean percent cover", x = "", fill = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, h = 1, face = "italic"))
```

Percent cover by site and species

```{r}
# calculating percent cover by species at each meter
rf_pc_spp_m <- rf_benthic %>%
  filter(av_sub_yn == "yes") %>%
  expand(nesting(site, transect, meter), nesting(species, cat_c)) %>%
  left_join(rf_benthic %>% 
              filter(av_sub_yn == "yes") %>% 
              group_by(site, transect, meter) %>%
              mutate(n_pts = n()) %>% 
              ungroup() %>%
              group_by(site, transect, meter, n_pts, species, cat_c) %>%
              summarize(pc_m = 100*n()/n_pts) %>%
              ungroup() %>%
              distinct() %>%
              select(-n_pts), 
            by = c("site", "transect", "meter", "species", "cat_c")) %>%
  mutate(pc_m = if_else(is.na(pc_m), 0, pc_m))

# calculating mean percent cover by transect -> site
rf_pc_spp_site <- rf_pc_spp_m %>%
  group_by(site, transect, species, cat_c) %>%
  summarize(pc_t = mean(pc_m)) %>%
  ungroup() %>%
  group_by(site, species, cat_c) %>%
  summarize(pc_mean = mean(pc_t),
            pc_se = sd(pc_t)/sqrt(n())
            ) %>%
  ungroup() %>%
  distinct()

# calculating mean percent cover by species across all sites
rf_pc_spp <- rf_pc_spp_site %>%
  group_by(species, cat_c) %>%
  summarize(pc = mean(pc_mean),
            pc_se = sd(pc_mean)/sqrt(n())) %>%
  rename(pc_mean = pc) 

# testing that total percent cover per transect and site add up to 100
test1 <- rf_pc_spp_m %>%
  group_by(site, transect, meter) %>%
  summarize(total = sum(pc_m))
test2 <- rf_pc_spp_site %>%
  group_by(site) %>%
  summarize(total = sum(pc_mean))
test3 <- sum(rf_pc_spp$pc_mean)

# graphs
ggplot(rf_pc_spp %>%
         filter(cat_c == "Hard corals"),
       aes(x = species, y = pc_mean)) +
  geom_col(fill = "blue", color = "black", alpha = 0.9) +
  labs(y = "Mean percent cover", x = "Species", fill = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, h = 1, face = "italic"))
```

# Fish

```{r}
# import and clean data

rf_fish <- read_excel(here("mma", "data", "mma_coral_fish.xlsx"), sheet = "fish") %>%  
  clean_names() %>%
  filter(!is.na(site)) %>% # remove any incomplete rows at the end of the data
  mutate(number = if_else(is.na(number), 1, number)) %>% # all entries with no number specified were single observations
  uncount(number) %>% # expand to replicate rows if multiple fish were recorded to look at length distributions
  mutate(biomass = as.numeric(biomass),
         phase_code = tolower(phase),
         phase = case_when(phase == "j" ~ "Juvenile",
                           phase == "i" ~ "Initial",
                           phase == "t" ~ "Terminal"),
         family_c = if_else(family %in% c("Scaridae", "Acanthuridae", "Haemulidae", "Serranidae", "Lutjanidae", "Balistidae", "Pomacentridae"), family, "Other")
         ) # consolidating the number of families
```

Mean total biomass by site
```{r}
# calculating total biomass in each transect (sum) -> mean at each site
rf_fish_site <- rf_fish %>% 
  group_by(site, transect) %>%
  summarize(bm_tot = sum(biomass)/1000/120*10000) %>% #kg/ha
  group_by(site) %>%
  summarize(bm_mean = mean(bm_tot),
            bm_se = sd(bm_tot)/sqrt(n()))

ggplot(rf_fish_site, aes(x = site, y = bm_mean)) +
  geom_col(fill = "lightblue", color = "black", alpha = 0.8) +
  geom_errorbar(aes(ymin = bm_mean - bm_se, ymax = bm_mean + bm_se), width = .2,
                 position = position_dodge(.9)) +
  labs(x = "Site", y = "Biomass (kg/ha)") +
  theme_bw()
```

Mean biomass by site and family
```{r}
rf_fish_fam_site <- rf_fish %>% 
  expand(nesting(site, transect), family_c) %>%
  left_join(rf_fish %>%
      select(site, transect, family_c, length, biomass)) %>%
  mutate(biomass = if_else(is.na(biomass), 0, biomass)) %>%
  group_by(site, transect, family_c) %>%
  summarize(bm_tot = sum(biomass)/1000/120*10000) %>% #kg/ha
  group_by(site, family_c) %>%
  summarize(bm_mean = mean(bm_tot),
            bm_se = sd(bm_tot)/sqrt(n()))

ggplot(rf_fish_fam_site, aes(x = family_c, y = bm_mean)) +
  geom_col(fill = "lightblue", color = "black", alpha = 0.8) +
  geom_errorbar(aes(ymin = bm_mean - bm_se, ymax = bm_mean + bm_se), width = .2,
                 position = position_dodge(.9)) +
  facet_wrap(. ~ site) +
  labs(x = "Site", y = "Biomass (kg/ha)") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, h = 1))
```

Biomass by species across all sites
```{r}
# calculate mean biomass by species for each transect -> site -> mean across sites
rf_fish_spp <- rf_fish %>% 
  expand(nesting(site, transect), species_code) %>%
  left_join(rf_fish %>%
      select(site, transect, species_code, length, biomass)) %>%
  mutate(biomass = if_else(is.na(biomass), 0, biomass)) %>%
  group_by(site, transect, species_code) %>%
  summarize(bm_tot = sum(biomass)/1000/120*10000) %>% #kg/ha
  group_by(site, species_code) %>%
  summarize(bm_mean = mean(bm_tot),
            bm_se = sd(bm_tot)/sqrt(n())) %>%
  group_by(species_code) %>%
  summarize(bm = mean(bm_mean),
            bm_se = sd(bm_mean)/sqrt(n())) %>%
  rename(bm_mean = bm) %>%
  left_join(rf_fish %>% 
              select(species_code, species_name, common_name, functional_group) %>%
              distinct())

# graph
ggplot(rf_fish_spp, aes(x = reorder(species_name, bm_mean), y = bm_mean)) +
  geom_col(fill = "lightblue", color = "black", alpha = 0.8) +
  geom_errorbar(aes(ymin = bm_mean - bm_se, ymax = bm_mean + bm_se), width = .2,
                 position = position_dodge(.9)) +
  coord_flip() +
  labs(x = "Site", y = "Biomass (kg/ha)") +
  theme_bw() +
  theme(axis.text.y = element_text(face = "italic"))
```


Something with fish length...? (same scarid phase/size graphs? Overall fish length distribution?)