---
title: "Little Ffryes EIA"
author: "Molly Wilson"
date: "2024-12-08"
output: html_document
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl)
library(janitor)
library(knitr)
library(snakecase) # for adjusting capitalization of text within data (e.g., species names)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
```

## Seagrass
```{r}
sg_quadrants <- read_excel(here("eias", "little_ffryes", "data_raw", "Little Ffryes seagrass data.xlsx"), sheet = "quadrants") %>% 
  unite("transect", 3:4, sep = "_", remove = TRUE) %>%
  clean_names() %>%
  mutate(code = tolower(code))

sg_quad_exp <- sg_quadrants %>%
  expand(transect, quadrant, species) %>%
  left_join(sg_quadrants %>% select(transect, quadrant, species, percent)) %>%
  mutate(percent = replace_na(percent, 0)) %>%
  left_join(sg_quadrants %>% select(species, code, category), by ="species") %>%
  distinct()

test1 <- sg_quadrants %>%
  group_by(transect, quadrant) %>%
  summarize(total = sum(percent)) %>%
  filter(total != 100)

test2 <- sg_quad_exp %>%
  group_by(transect, quadrant) %>%
  summarize(total = sum(percent)) %>%
  filter(total != 100)

sg_cover_cat <- sg_quad_exp %>%
  group_by(transect, quadrant, category) %>%
  summarize(percent_cat = sum(percent)) %>%
  group_by(transect, category) %>%
  summarize(percent_tran = mean(percent_cat),
            se = sd(percent_cat)/sqrt(10)) %>%
  group_by(category) %>%
  summarize(percent_tot = mean(percent_tran),
            se = sd(percent_tran)/sqrt(12)) %>%
  mutate(category = fct_relevel(category, c("Seagrass", "Macroalgae", "Stony coral", "Sponges & soft coral", "Bare substrate")))
write.csv(sg_cover_cat, here("eias", "little_ffryes", "data_outputs", "sg_cover_cat.csv"))

sg_cover_spp <- sg_quad_exp %>%
  group_by(transect, category, species) %>%
  summarise(percent_tran = mean(percent),
            se = sd(percent)/sqrt(10)) %>%
  group_by(category, species) %>%
  summarise(percent_tot = mean(percent_tran),
            se = sd(percent_tran)/sqrt(12)) %>%
  ungroup() %>%
  mutate(species = fct_reorder(species, desc(species)),
         status = if_else(species == "Halophila stipulacea", "Invasive", "Native")) 
write.csv(sg_cover_spp, here("eias", "little_ffryes", "data_outputs", "sg_cover_spp.csv"))
```
```{r}
color_algae <- "darkolivegreen"
color_seagrass <- "darkgreen"
color_coral <- "coral"
color_sponges <- "goldenrod"
color_baresub <- "slategray"

ggplot(sg_cover_cat, aes(x = category, y = percent_tot)) +
  geom_col(color = "black", aes(fill = category)) +
  geom_errorbar(aes(ymin = percent_tot - se, ymax = percent_tot + se), width = .2) +
  ylim(0, 100) +
  scale_fill_manual(values = c(color_seagrass, color_algae, color_coral, color_sponges, color_baresub)) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "", y = "Mean percent cover")
ggsave(here("eias", "little_ffryes", "figs", "sg_cover_cat.png"), width = 6, height = 4)

ggplot(sg_cover_spp %>% filter(category == "Seagrass"), aes(x = species, y = percent_tot, group = category)) +
  geom_col(fill = color_seagrass, color = "black") +
  coord_flip() +
  geom_errorbar(aes(ymin = percent_tot - se, ymax = percent_tot + se), width = .2) +
  labs(x = "", y = "Mean percent cover") +
  theme_bw() +
  theme(axis.text.y = element_text(face = "italic"))
ggsave(here("eias", "little_ffryes", "figs", "cover_seagrass.png"), width = 6, height = 2)

ggplot(sg_cover_spp %>% filter(category == "Macroalgae") %>% arrange(species, percent_tot), aes(x = species, y = percent_tot, group = category)) +
  geom_col(fill = color_algae, color = "black") +
  coord_flip() +
  scale_x_discrete(labels = labs) +
  geom_errorbar(aes(ymin = percent_tot - se, ymax = percent_tot + se), width = .2) +
  labs(x = "", y = "Mean percent cover") +
  theme_bw() +
  theme(axis.text.y = element_text(face = "italic")) # change to have second word non-italic
ggsave(here("eias", "little_ffryes", "figs", "cover_algae.png"), width = 6, height = 4)

ggplot(sg_cover_spp %>% filter(category == "Stony coral") %>% arrange(species, percent_tot), aes(x = species, y = percent_tot, group = category)) +
  geom_col(fill = color_coral, color = "black") +
  coord_flip() +
  geom_errorbar(aes(ymin = percent_tot - se, ymax = percent_tot + se), width = .2) +
  labs(x = "", y = "Mean percent cover") +
  theme_bw() +
  theme(axis.text.y = element_text(face = "italic"))
ggsave(here("eias", "little_ffryes", "figs", "cover_coral.png"), width = 6, height = 2)

# ggplot(sg_cover_spp %>% filter(category == "Bare substrate") %>% arrange(species, percent_tot), aes(x = species, y = percent_tot, group = category)) +
#   geom_col(fill = "slategray", color = "black") +
#   coord_flip() +
#   geom_errorbar(aes(ymin = percent_tot - se, ymax = percent_tot + se), width = .2) +
#   labs(x = "", y = "Mean percent cover") +
#   theme_bw()
# ggsave(here("eias", "little_ffryes", "figs", "cover_substrate.png"), width = 6, height = 2)
```