---
title: "GB monitoring"
author: "Molly Wilson"
date: "11/24/2021"
output: html_document
---

```{r, message = F, warning = F, echo = F}
library(tidyverse)
library(here) 
library(readxl) 
library(janitor)
library(knitr)
library(stringr)
library(RColorBrewer)
library(lubridate)
library(scales)

knitr::opts_chunk$set(message = FALSE, warning = FALSE)
Sys.setenv(TZ="America/Guadeloupe")
```

```{r}
sources <- read_excel(here("nursery_monitoring", "frag sources.xlsx"), sheet = "sources") %>%  
  clean_names() %>%
  mutate(site = replace(site, site == "Cervi Heaven", "North Green")) %>%
  select(source = site, genotype = id_number) %>%
  mutate(source = factor(source, levels = c("Little Bird Channel", "Great Bird", "Hells Gate", "North Green", "Man of War", "York Island", "Friar's Head", "Exchange Bay")))

YlGnBu <- brewer.pal(8,"Set3")
names(YlGnBu) <- levels(sources$source)
colScale <- scale_colour_manual(name = "source",values = YlGnBu)

apal <- read_excel(here("nursery_monitoring", "gb monitoring.xlsx"), sheet = "palmata") %>%  
  clean_names() %>%
  mutate(species = "A. palmata") %>%
  filter(!is.na(m1)) %>%
  unite(id, genotype, position, iteration, sep = "_", remove = FALSE) %>%
  mutate(area = m1*m2,
         sum = m1 + m2,
         month = lubridate::month(date, label = TRUE, abbr = TRUE)) %>%
  left_join(sources, by = "genotype")

acer <- read_excel(here("nursery_monitoring", "gb monitoring.xlsx"), sheet = "cervicornis") %>%  
  clean_names() %>%
  mutate(species = "A. cervicornis") %>%
  unite(id, genotype, position, iteration, sep = "_", remove = FALSE) %>%
  pivot_longer(cols = starts_with("m"), names_to = "branch", values_to = "length") %>%
  filter(!is.na(length)) %>%
  filter(!(length < 1 & date == as.Date("2021-10-07"))) %>% # was likely overmeasuring small branches
  group_by(id, genotype, date) %>%
  summarize(tle = sum(length)) %>%
  ungroup() %>%
  mutate(tle = if_else(date == as.Date("2021-12-01"), tle + 1, tle), # forgot to measure crimp
                       month = lubridate::month(date, label = TRUE, abbr = TRUE)) %>% 
  left_join(sources, by = "genotype")
  
apro <- read_excel(here("nursery_monitoring", "gb monitoring.xlsx"), sheet = "prolifera") %>%  
  clean_names() %>%
  mutate(species = "A. prolifera") %>%
  unite(id, genotype, position, iteration, sep = "_", remove = FALSE) %>%
  pivot_longer(cols = starts_with("m"), names_to = "branch", values_to = "length") %>%
  filter(!is.na(length)) %>%
  group_by(id, genotype, date) %>%
  summarize(tle = sum(length)) %>%
  ungroup() %>%
  mutate(tle = if_else(date == as.Date("2021-12-01"), tle + 1, tle), # forgot to measure crimp
          month = lubridate::month(date, label = TRUE, abbr = TRUE)) %>%
  left_join(sources, by = "genotype")
```

Quantifying growth: A. cervicornis
```{r}
n_mo <- n_distinct(acer$date)

acer_growth_long <- acer %>%
  group_by(id) %>%
  summarize(count = n()) %>%
  filter(count >= n_mo-1) %>%
  left_join(acer)

acer_growth_wide <- acer %>%
  pivot_wider(id_cols = c(id, genotype, source), names_from = date, values_from = tle) %>%
  mutate(growth = .[[n_mo + 3]] - .[[4]],
         growth_percent = growth/.[[4]]) %>%
  filter(!is.na(growth))

acer_growth_sum <- acer_growth_wide %>%
  group_by(genotype, source) %>%
  summarize(mean_growth = mean(growth),
            se = sd(growth)/sqrt(n()),
            mean_growth_p = mean(growth_percent),
            se_p = sd(growth_percent)/sqrt(n())) %>%
   mutate(source = factor(source, levels = c("Little Bird Channel", "Great Bird", "Hells Gate", "North Green", "Man of War", "York Island", "Friar's Head", "Exchange Bay")))

ggplot(acer_growth_long, aes(x = date, y = tle, group = id)) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(genotype)) +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_acer_line.png"), width = 6, height = 4)

ggplot(acer_growth_sum, aes(x = genotype, y = mean_growth)) +
  geom_col(aes(fill = source), color = "black") +
  scale_fill_manual(values = YlGnBu) +
  geom_errorbar(aes(ymin = mean_growth - se, ymax = mean_growth + se), width = .2) +
  labs(y = "Mean fragment growth (Aug. 2021 - Jan. 2022)", x = "Genotype", fill = "Source") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_acer_bar.png"), width = 6, height = 4)
```

Quantifying growth: A. prolifera
```{r}
n_mo <- n_distinct(apro$date)

apro_growth_long <- apro %>%
  group_by(id) %>%
  summarize(count = n()) %>%
  filter(count >= n_mo-1) %>%
  left_join(apro)

apro_growth_wide <- apro %>%
  pivot_wider(id_cols = c(id, genotype, source), names_from = date, values_from = tle) %>%
  mutate(growth = .[[n_mo + 3]] - .[[4]],
         growth_percent = growth/.[[4]]) %>%
  filter(!is.na(growth))

apro_growth_sum <- apro_growth_wide %>%
  group_by(genotype, source) %>%
  summarize(mean_growth = mean(growth),
            se = sd(growth)/sqrt(n()),
            mean_growth_p = mean(growth_percent),
            se_p = sd(growth_percent)/sqrt(n())) %>%
   mutate(source = factor(source, levels = c("Little Bird Channel", "Great Bird", "Hells Gate", "North Green", "Man of War", "York Island", "Friar's Head", "Exchange Bay")))

ggplot(apro_growth_long, aes(x = date, y = tle, group = id)) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(genotype)) +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apro_line.png"), width = 6, height = 4)

ggplot(apro_growth_sum, aes(x = genotype, y = mean_growth)) +
  geom_col(aes(fill = source), color = "black") +
  scale_fill_manual(values = YlGnBu) +
  geom_errorbar(aes(ymin = mean_growth - se, ymax = mean_growth + se), width = .2) +
  labs(y = "Mean fragment growth (Aug. 2021 - Jan. 2022)", x = "Genotype", fill = "Source") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apro_bar.png"), width = 6, height = 4)
```

Quantifying growth: A. palmata
```{r}
n_mo <- n_distinct(apal$date)

apal_growth_long <- apal %>%
  group_by(id) %>%
  summarize(count = n()) %>%
  filter(count >= max(count-1)) %>%
  left_join(apal)

apal_growth_wide <- apal %>%
  pivot_wider(id_cols = c(id, genotype, source), names_from = date, values_from = sum) %>%
  mutate(growth = .[[n_mo + 3]] - .[[4]],
         growth_percent = growth/.[[4]]) %>%
  filter(!is.na(growth))

apal_growth_sum <- apal_growth_wide %>%
  group_by(genotype, source) %>%
  summarize(mean_growth = mean(growth),
            se = sd(growth)/sqrt(n()),
            mean_growth_p = mean(growth_percent),
            se_p = sd(growth_percent)/sqrt(n())) %>%
   mutate(source = factor(source, levels = c("Little Bird Channel", "Great Bird", "Hells Gate", "North Green", "Man of War", "York Island", "Friar's Head", "Exchange Bay")))

ggplot(apal_growth_long, aes(x = date, y = sum, group = id)) +
  geom_point() +
  geom_line() +
  facet_wrap(vars(genotype)) +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apal_line.png"), width = 6, height = 6)

ggplot(apal_growth_sum, aes(x = genotype, y = mean_growth)) +
  geom_col(aes(fill = source), color = "black") +
  scale_fill_manual(values = YlGnBu) +
  geom_errorbar(aes(ymin = mean_growth - se, ymax = mean_growth + se), width = .2) +
  labs(y = "Mean fragment growth (Aug. 2021 - Jan. 2022)", x = "Genotype", fill = "Source") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apal_bar.png"), width = 6, height = 4)
```
Quantifying apal hands/crimp overgrowth
```{r}
apal_qual <- apal %>%
  filter(date == as.Date("2022-03-01") & !is.na(m1)) %>%
  mutate(crimp_overgrowth = if_else(crimp_overgrowth == "Y", 1, 0)) %>%
  group_by(genotype, source) %>%
  summarize(n = n(),
            p_overgrowth = mean(crimp_overgrowth)*100,
            n_hands_mean = mean(n_hands),
            n_hands_se = sd(n_hands)/sqrt(n))

ggplot(apal_qual, aes(x = genotype, y = p_overgrowth)) +
  geom_col(aes(fill = source), color = "black") +
  scale_fill_manual(values = YlGnBu) +
  #geom_errorbar(aes(ymin = mean_growth - se, ymax = mean_growth + se), width = .2) +
  labs(y = "Percent of fragments with crimp overgrowth", x = "Genotype", fill = "Source") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apal_crimp.png"), width = 6, height = 4)

ggplot(apal_qual, aes(x = genotype, y = n_hands_mean)) +
  geom_col(aes(fill = source), color = "black") +
  scale_fill_manual(values = YlGnBu) +
  geom_errorbar(aes(ymin = n_hands_mean - n_hands_se, ymax = n_hands_mean + n_hands_se), width = .2) +
  labs(y = "Mean number of new growth appendages", x = "Genotype", fill = "Source") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apal_hands.png"), width = 6, height = 4)
```

Summary graphs for 2021 report 
- one for each species (different growth scales)
- (show fragment size at each timestep as percent of initial fragment size)
- only use fragments with all (6) timesteps
- create averages per genotype

```{r}
# ACER

acer_sum2 <- acer_growth_long %>%
  filter(count == n_mo) %>%
  group_by(genotype, date) %>%
  summarise(tle_mean = mean(tle)) %>%
  ungroup() %>%
  mutate(species = "ACER")

ggplot(acer_sum2, aes(x = date, y = tle_mean, group = genotype)) +
  geom_point() +
  geom_line() +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_acer_line_sum.png"), width = 6, height = 4)

# APRO

apro_sum2 <- apro_growth_long %>%
  filter(count == n_mo) %>%
  group_by(genotype, date) %>%
  summarise(tle_mean = mean(tle)) %>%
  ungroup() %>%
  mutate(species = "APRO")

ggplot(apro_sum2, aes(x = date, y = tle_mean, group = genotype)) +
  geom_point() +
  geom_line() +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apro_line_sum.png"), width = 6, height = 4)

# ACER ~ APRO

acerapro <- rbind(apro_sum2, acer_sum2)
ggplot(acerapro, aes(x = date, y = tle_mean, group = genotype)) +
  geom_point(color = "turquoise4") +
  geom_line(color = "turquoise4") +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() + 
  theme(axis.text = element_text(size = 14))
ggsave(here("nursery_monitoring", "figs", "growth_aproacer_line_jan.png"), width = 5, height = 3)

ggplot(acerapro, aes(x = date, y = tle_mean, group = genotype)) +
  geom_point() +
  geom_line() +
  facet_wrap(.~species) +
  labs(y = "Total linear extension (cm)", x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))



## APAL

apal_sum2 <- apal_growth_long %>%
  filter(count == n_mo) %>%
  group_by(genotype, month, date) %>%
  summarise(area_mean = mean(area))

ggplot(apal_sum2, aes(x = date, y = area_mean, group = genotype)) +
  geom_point() +
  geom_line() +
  labs(y = expression("Area ("~cm^2~")"), x = "") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggsave(here("nursery_monitoring", "figs", "growth_apal_line_sum.png"), width = 5, height = 4)


apal_sum3 <- apal_sum2 %>%
  group_by(month, date) %>%
  summarize(area = mean(area_mean),
            se = sd(area_mean)/sqrt(n())) %>%
  filter(month %in% c("Aug", "Mar"))

ggplot(apal_sum3, aes(x = reorder(month, date), y = area)) +
  geom_col(fill = "#97dce7") +
  geom_errorbar(aes(ymin = area - se, ymax = area + se), width = .2) +
  labs(y = expression("Mean fragment area ("~cm^2~")"), x = "") +
  theme_bw() + 
  theme(axis.text.x = element_text(size = 14))
ggsave(here("nursery_monitoring", "figs", "growth_apal_sum_mar.png"), width = 3, height = 3)

ggplot(apal %>% filter(month == "Jan"), aes(x = n_hands)) +
  geom_bar(aes(y = (..count..)/sum(..count..)), fill = "turquoise4") +
  scale_y_continuous(labels = percent, position = "right") +
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6)) +
  labs(y = "Percent of fragments", x = "Number of new appendages") +
  theme_bw() + 
  theme(axis.text = element_text(size = 10))
ggsave(here("nursery_monitoring", "figs", "growth_apal_hands_mar.png"), width = 3, height = 3)
```


